name:
  Spotify Archive Manual Data Ingestion

on: workflow_dispatch

jobs:
  cron:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Java JDK
        uses: actions/setup-java@4.7.1
        with:
          java-version: '17'
          distribution: 'temurin'


      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout spotify-playlist-archive repo
        uses: actions/checkout@v4
        with:
          repository: mackorone/spotify-playlist-archive
          sparse-checkout: |
            playlists/metadata/metadata-compact.json
            playlists/pretty

      - run: "ls; ls spotify-playlist-archive"

      - name: Ingest playlist data
        run: "./mvnw spring-boot:run"
        env:
          JDBC_CONNECTION_STRING: ${{ secrets.JDBC_CONNECTION_STRING }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SPOTIFY_ARCHIVE_ROOT_DIR: "./spotify-playlist-archive"
